---
include:
  #  - board: eyelash_corne_left
  #    shield: nice_view
  #    #snippet: zmk-usb-logging    # Uncomment to log over USB.
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
    artifact-name: corne_right
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: corne_left
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
